### YamlMime:ManagedReference
items:
- uid: PlusPim.Application
  commentId: N:PlusPim.Application
  id: PlusPim.Application
  children:
  - PlusPim.Application.Application
  - PlusPim.Application.ExceptionInfo
  - PlusPim.Application.IApplication
  - PlusPim.Application.IDebugger
  - PlusPim.Application.StackFrameInfo
  langs:
  - csharp
  - vb
  name: PlusPim.Application
  nameWithType: PlusPim.Application
  fullName: PlusPim.Application
  type: Namespace
  assemblies:
  - PlusPim
references:
- uid: PlusPim.Application.Application
  commentId: T:PlusPim.Application.Application
  href: PlusPim.Application.Application.html
  name: Application
  nameWithType: Application
  fullName: PlusPim.Application.Application
- uid: PlusPim.Application.ExceptionInfo
  commentId: T:PlusPim.Application.ExceptionInfo
  parent: PlusPim.Application
  href: PlusPim.Application.ExceptionInfo.html
  name: ExceptionInfo
  nameWithType: ExceptionInfo
  fullName: PlusPim.Application.ExceptionInfo
- uid: PlusPim.Application.IApplication
  commentId: T:PlusPim.Application.IApplication
  parent: PlusPim.Application
  href: PlusPim.Application.IApplication.html
  name: IApplication
  nameWithType: IApplication
  fullName: PlusPim.Application.IApplication
- uid: PlusPim.Application.IDebugger
  commentId: T:PlusPim.Application.IDebugger
  parent: PlusPim.Application
  href: PlusPim.Application.IDebugger.html
  name: IDebugger
  nameWithType: IDebugger
  fullName: PlusPim.Application.IDebugger
- uid: PlusPim.Application.StackFrameInfo
  commentId: T:PlusPim.Application.StackFrameInfo
  parent: PlusPim.Application
  href: PlusPim.Application.StackFrameInfo.html
  name: StackFrameInfo
  nameWithType: StackFrameInfo
  fullName: PlusPim.Application.StackFrameInfo
- uid: PlusPim.Application
  commentId: N:PlusPim.Application
  href: PlusPim.html
  name: PlusPim.Application
  nameWithType: PlusPim.Application
  fullName: PlusPim.Application
  spec.csharp:
  - uid: PlusPim
    name: PlusPim
    href: PlusPim.html
  - name: .
  - uid: PlusPim.Application
    name: Application
    href: PlusPim.Application.html
  spec.vb:
  - uid: PlusPim
    name: PlusPim
    href: PlusPim.html
  - name: .
  - uid: PlusPim.Application
    name: Application
    href: PlusPim.Application.html
